'use strict';

// Scenario registry. `expected` is what CONTEXT.md says should happen; the
// actual PR #46 behaviour is measured by run-scenarios.js and pinned in
// test/scenarios.test.js.

const fixture = (name) => require(`./fixtures/${name}`);

const SCENARIOS = [
    {
        id: 'bittorrent-dht',
        title: 'BitTorrent/DHT: 300 peers, UDP 6881/51413, 60 s',
        group: 'false-positive',
        generate: () => fixture('bittorrent-dht').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: torrent ports isolated, never feed scan rules',
    },
    {
        id: 'bittorrent-tcp',
        title: 'Variant: same 300 peers over TCP',
        group: 'false-positive',
        generate: () => fixture('bittorrent-dht').generate({ network: 'tcp' }),
        expected: 'no action',
        basis: 'CONTEXT §2: torrent ports isolated, never feed scan rules',
    },
    {
        id: 'dns-benchmark',
        title: 'DNS benchmark: 40 resolvers on :53 in 1 s, 5 users (UDP)',
        group: 'false-positive',
        generate: () => fixture('dns-benchmark').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: port 53 is diagnostics-only',
    },
    {
        id: 'dns-benchmark-tcp',
        title: 'Variant: same benchmark over TCP',
        group: 'false-positive',
        generate: () => fixture('dns-benchmark').generate({ network: 'tcp' }),
        expected: 'no action',
        basis: 'CONTEXT §2: port 53 is diagnostics-only',
    },
    {
        id: 'ntp-pool',
        title: 'NTP pool client: 120 servers on :123, ~3 hits each',
        group: 'false-positive',
        generate: () => fixture('ntp-pool').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: NTP is diagnostics-only',
    },
    {
        id: 'steam-webrtc-xmpp',
        title: 'Steam game + WebRTC call + XMPP chat, 1 h',
        group: 'false-positive',
        generate: () => fixture('steam-webrtc-xmpp').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: game/realtime ports dropped before analysis',
    },
    {
        id: 'imap-polling',
        title: 'IMAP client polling :993 every 2-4 s for 1 h',
        group: 'false-positive',
        generate: () => fixture('imap-polling').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: mail ports, never act',
    },
    {
        id: 'heavy-browser',
        title: 'Heavy browser: 600 HTTPS destinations in 15 min',
        group: 'false-positive',
        generate: () => fixture('heavy-browser').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: web floods are not a DoS signal',
    },
    {
        id: 'app-peers-50300',
        title: 'App contacting 80 new peers per burst on :50300, 6 bursts/h',
        group: 'false-positive',
        generate: () => fixture('app-peers-high-port').generate({ port: 50300 }),
        expected: 'no action',
        basis: 'real data: top blocked port, app traffic',
    },
    {
        id: 'app-peers-8887',
        title: 'Same app pattern on :8887',
        group: 'false-positive',
        generate: () => fixture('app-peers-high-port').generate({ port: 8887, seed: 8887 }),
        expected: 'no action',
        basis: 'real data: blocked app port',
    },
    {
        id: 'lan-sync',
        title: 'LAN sync discovery: /24 walks on :53317 (every 5 min) and :62078 (every 15 min)',
        group: 'false-positive',
        generate: () => fixture('lan-sync').generate(),
        expected: 'no action',
        basis: 'real data: 53317 and 62078 blocks',
    },
    {
        id: 'heavy-browser-domains',
        title: 'Heavy browsing by name: 600 hostnames, 400 domains, 443/80, 15 min',
        group: 'false-positive',
        generate: () => fixture('heavy-browser-domains').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: web floods are not a DoS signal',
    },
    {
        id: 'api-poller',
        title: 'API poller: 2 req/s on :8443 (IP and name), push on :5228, 1 h',
        group: 'false-positive',
        generate: () => fixture('api-poller').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: proxy/alt ports and push are not scans',
    },
    {
        id: 'imap-domain',
        title: 'IMAP by name: imap.mail.example:993 every 2-4 s, 1 h',
        group: 'false-positive',
        generate: () => fixture('imap-domain').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: mail ports, never act',
    },
    {
        id: 'ssh-jump-hosts',
        title: '5 SSH jump hosts under one domain, a session every 10-40 s, 1 h',
        group: 'false-positive',
        generate: () => fixture('ssh-jump-hosts').generate(),
        expected: 'no action',
        basis: 'normal administration',
    },
    {
        id: 'cdn-shards',
        title: '300 CDN shard hostnames on 443, 4 rounds in 1 h',
        group: 'false-positive',
        generate: () => fixture('cdn-shards').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: web',
    },
    {
        id: 'tracker-announce',
        title: 'Tracker announces by name on :6969, 40 trackers every 5 min',
        group: 'false-positive',
        generate: () => fixture('tracker-announce').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: torrent ports never feed scan rules',
    },
    {
        id: 'game-launcher',
        title: 'Game launcher: 30 domains on 443/7777/27015-27030, then a game session',
        group: 'false-positive',
        generate: () => fixture('game-launcher').generate(),
        expected: 'no action',
        basis: 'CONTEXT §2: game ports dropped before analysis',
    },
    {
        id: 'cgnat-shared-ip',
        title: 'CGNAT: 50 users on one IP, one scanning',
        group: 'structural',
        generate: () => fixture('cgnat-shared-ip').generate(),
        expected: 'flag the scanning user; do not block the shared IP',
        basis: 'CONTEXT §3.1: blocking the IP punishes everyone behind it',
    },
    {
        id: 'chained-exit-node',
        title: 'Chained exit node: 2,000 people as one userId from one internal IP',
        group: 'structural',
        generate: () => fixture('chained-exit-node').generate(),
        expected: 'never block; report-only at most',
        basis: 'CONTEXT §3.2: detect chained/technical inbounds and never block there',
    },
    {
        id: 'chained-exit-node-no-torrent',
        title: 'Variant: same, with nobody running BitTorrent',
        group: 'structural',
        generate: () => fixture('chained-exit-node').generate({ torrentShare: 0 }),
        expected: 'never block; report-only at most',
        basis: 'CONTEXT §3.2',
    },
    {
        id: 'tp-ssh-sweep',
        title: 'SSH sweep: 200 /24s on :22, random order, 2 min',
        group: 'true-positive',
        generate: () => fixture('tp-ssh-sweep').generate({ order: 'random' }),
        expected: 'flag (horizontal_sweep_hard: >=150 /24s on a recon port in 15 min)',
        basis: 'CONTEXT §1',
    },
    {
        id: 'tp-ssh-sweep-sequential',
        title: 'Variant: 200 /24s x 25 hosts, sequential, 500/min',
        group: 'true-positive',
        generate: () => fixture('tp-ssh-sweep').generate({ order: 'sequential' }),
        expected: 'flag (horizontal_sweep_hard)',
        basis: 'CONTEXT §1',
    },
    {
        id: 'tp-rtsp-sweep',
        title: 'RTSP sweep: 200 /24s each on 554 and 553, 2 min',
        group: 'true-positive',
        generate: () => fixture('tp-rtsp-sweep').generate(),
        expected: 'flag (horizontal_sweep_hard on 554 and 553)',
        basis: 'CONTEXT §1',
    },
    {
        id: 'tp-rdp-hammer',
        title: '300 sessions to one host on :3389 in 10 min',
        group: 'true-positive',
        generate: () => fixture('tp-rdp-hammer').generate(),
        expected: 'flag (hammer_target: >=300 sessions to one dst/recon port in 15 min)',
        basis: 'CONTEXT §1',
    },
    {
        id: 'tp-rdp-hammer-400',
        title: '400 sessions to one IP on :3389 in 13 min',
        group: 'true-positive',
        generate: () => fixture('tp-rdp-hammer-host').generate({ sessionsCount: 400, target: 'ip' }),
        expected: 'flag (hammer_target)',
        basis: 'CONTEXT §1',
    },
    {
        id: 'tp-rdp-hammer-host-300',
        title: '300 sessions to one hostname on :3389 in 10 min',
        group: 'true-positive',
        generate: () => fixture('tp-rdp-hammer-host').generate({ sessionsCount: 300, target: 'host' }),
        expected: 'flag (hammer_target)',
        basis: 'CONTEXT §1',
    },
    {
        id: 'tp-rdp-hammer-host-400',
        title: '400 sessions to one hostname on :3389 in 13 min',
        group: 'true-positive',
        generate: () => fixture('tp-rdp-hammer-host').generate({ sessionsCount: 400, target: 'host' }),
        expected: 'flag (hammer_target)',
        basis: 'CONTEXT §1',
    },
    ...[25, 50, 500].map((rate) => ({
        id: `tp-ssh-random-${rate}`,
        title: `Random-order SSH sweep, ${rate} targets/min for 15 min`,
        group: 'true-positive',
        generate: () => fixture('tp-ssh-random-rate').generate({ ratePerMinute: rate }),
        expected: 'flag (horizontal_sweep_hard)',
        basis: 'CONTEXT §1',
    })),
    {
        id: 'tp-ssh-hostnames',
        title: 'SSH scan of 500 hostnames across 400 domains, 10 min',
        group: 'true-positive',
        generate: () => fixture('tp-ssh-hostnames').generate(),
        expected: 'flag (sweep by name)',
        basis: 'design: horizontal_sweep_domains',
    },
    {
        id: 'tp-subdomain-enum',
        title: 'Subdomain enumeration: 200 hostnames under one domain on :22 and :3389, 10 min',
        group: 'true-positive',
        generate: () => fixture('tp-subdomain-enum').generate(),
        expected: 'flag (report)',
        basis: 'design: subdomain_sweep',
    },
    {
        id: 'tp-mixed-telnet',
        title: 'Telnet scan mixing 300 IPs and 200 hostnames (150 domains), 10 min',
        group: 'true-positive',
        generate: () => fixture('tp-mixed-telnet').generate(),
        expected: 'flag (horizontal_sweep_hard)',
        basis: 'CONTEXT §1',
    },
    {
        id: 'tp-midnight',
        title: 'Random SSH sweep, 20/min from 23:52 to 00:07, replayed continuously',
        group: 'true-positive',
        generate: () => fixture('tp-midnight').generate(),
        expected: 'flag (horizontal_sweep_hard)',
        basis: 'real-data caveat: per-day replays split this scan',
    },
    {
        id: 'tp-session-burst',
        title: '700 non-web sessions in 60 s (5 DB hosts)',
        group: 'true-positive',
        generate: () => fixture('tp-session-burst').generate(),
        expected: 'flag (session_rate_burst: >=600 non-web sessions in 60 s)',
        basis: 'CONTEXT §1',
    },
];

module.exports = { SCENARIOS };
